---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-project # name of cluster
  region: us-east-1
  version: "1.20" # kubernetes version
vpc: # Refer: https://github.com/weaveworks/eksctl/blob/main/examples/04-existing-vpc.yaml
  id: "vpc-0e3bee40e6a42a107"
  subnets:
    public:
      capstoneproject-eks-public-subnet-a:
        id: "subnet-0eb2d50d719087bf9"
        az: "us-east-1a"
      capstoneproject-eks-public-subnet-b:
        id: "subnet-09b145003460b5e93"
        az: "us-east-1b"
    private:
      capstoneproject-eks-private-subnet-a:
        id: "subnet-02922b9cd2b4a03ed"
        az: "us-east-1a"
      capstoneproject-eks-private-subnet-b:
        id: "subnet-0ec14c66d4425daa8"
        az: "us-east-1b"
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true
  nat:
    gateway: Disable # disable since already created

iam: # Refer: https://eksctl.io/usage/iamserviceaccounts/
  withOIDC: true
  serviceAccounts: # pre-including some common iamserviceaccounts
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: efs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      efsCSIController: true
  - metadata:
      name: external-dns
      namespace: kube-system
    wellKnownPolicies:
      externalDNS: true
  - metadata:
      name: cert-manager
      namespace: cert-manager
    wellKnownPolicies:
      certManager: true
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    wellKnownPolicies:
      autoScaler: true

nodeGroups: # Refer: https://github.com/weaveworks/eksctl/blob/main/examples/05-advanced-nodegroups.yaml
  - name: pvt-capstoneproject-a-1
    labels: { role: workers }
    tags:
      k8s.io/cluster-autoscaler/enabled: "true" # tag is needed for cluster autoscaler. Refer: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup
      k8s.io/cluster-autoscaler/capstone-project: "shared" # cluster name tag is optional in latest versions of EKS
    instancesDistribution:
      instanceTypes:
        - t2.medium
    desiredCapacity: 1
    minSize: 0
    maxSize: 3
    privateNetworking: true # include only in private subnet
    subnets:
      - capstoneproject-eks-private-subnet-a # 1 AZ is enough for testing
  - name: pub-capstoneproject-a-1
    labels: { role: workers }
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/capstone-project: "shared"
    instancesDistribution:
      instanceTypes:
        - t2.medium
    desiredCapacity: 1
    minSize: 0
    maxSize: 1
    subnets:
      - capstoneproject-eks-public-subnet-a
